### ISSUE TITLE
Are new translations accepted as contributions?

### ISSUE THREAD

**Issue by matheusinfo** [us3rT0m/OnlyUP-Trainer#11]
I wanted to add new translations to the Only Up trainer, including translations for Brazilian Portuguese and Spanish. Are these contributions accepted or is there already someone working on this??

**Comment by us3rT0m** [comment]
hello, i don't have time to work on this project anymore. I'm sorry. My friend edgar is the admin of the community and he will take care of the project now. Here is the new repo : https://github.com/Edgarflc/OnlyUP-Trainer
