### ISSUE TITLE
Run Non Trouve #2

### ISSUE THREAD

**Issue by samkley** [us3rT0m/OnlyUP-Trainer#12]
I launch only up as admin and trainer as admin yet when i initialize i get this error
![image](https://github.com/us3rT0m/OnlyUP-Trainer/assets/110097208/12c8fbb6-75c5-4489-b284-b179c85e0872)
any way to fix it?

**Comment by wRadion** [comment]
Are you sure you're on the last version of the game (e.g. not a cracked version)?

If yes, then just restart either the game or the Trainer and start again.

**Comment by samkley** [comment]
It is a cracked version

**Comment by wRadion** [comment]
Then sorry but it's not compatible with the Trainer.
